# Generated by Django 4.0.4 on 2022-05-08 20:57

from django.db import migrations, models
import paslaugos.models


class Migration(migrations.Migration):

    dependencies = [
        ('paslaugos', '0002_alter_post_updatedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=paslaugos.models.upload_to),
        ),
    ]
