# Generated by Django 4.0.4 on 2022-05-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paslaugos', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
