version: "3.8"

services:
  db:
    restart: always
    image: postgres
    container_name: bakalauras-postgres #you can change this
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2288
      - POSTGRES_DB=paslaugosdb
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/usr/src/app
    ports:
        - "8000:8000"
    depends_on:
      - db


volumes:
  postgres_data:
